### ISSUE TITLE
(error): unable to create synchronization session

### ISSUE THREAD

**Issue by Guikingone** [mutagen-io/mutagen-compose#2]
Hi Mutagen team 👋🏻 

I'm facing a small issue when it comes to using the compose version of Mutagen, here's the context: 

**macOS**: 

```bash
macOS Monterey (12.0.1)
M1 Pro ship
```

**Docker version (Docker Desktop)**:

```bash
4.2.0

Docker engine: v20.10.10
Docker-Compose: 2.1.1
```

**Mutagen version**: 

```bash
0.13.0-beta2
```

**Mutagen-Compose version**: 

```bash
0.13.0-beta2
```

Here's the error: 

```bash
Resuming existing forwarding sessions
Resuming existing synchronization sessions                                      
Creating synchronization session "php"                                          
Connecting to agent (POSIX)...                                                  
Error: unable to reconcile Mutagen sessions: unable to create synchronization session (php): unable to connect to beta: unable to connect to endpoint: unable to dial agent endpoint: unable to create agent command: unable to probe container: container probing failed under POSIX hypothesis (exit status 1) and Windows hypothesis (exit status 1)
```

I just saw that someone already faced the issue but it was on an earlier version: https://githubmemory.com/repo/mutagen-io/mutagen/issues/298 so it seems strange 🤔 

Thanks for the feedback and have a great day 🙂

**Comment by xenoscopic** [comment]
@Guikingone Based on the output you provided, it looks like you're still using the `mutagen compose` command.  You'll need to use the `mutagen-compose` command and not the `mutagen compose` command. The latter still refers to Compose V1 integration, which is wrapping the `docker-compose` command (which is most likely pointed at Compose V2).  The new `mutagen-compose` command is a Compose V2 implementation.

I know it's kind of a confusing setup at the moment, especially since `docker-compose` can magically redirect to Compose V2 if Docker Desktop opts you in.  Hopefully it should all calm down in a few more weeks.

Let me know if that doesn't fix the issue.
